apiVersion: apps/v1
kind: Deployment
metadata:
  name: spam-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spam-app
  template:
    metadata:
      labels:
        app: spam-app
    spec:
      containers:
      - name: flask-app-container
        image: akash300/spam:1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: spam-app-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32002
  selector:
    app: spam-app
