apiVersion: apps/v1
kind: Deployment
metadata:
  name: spam:9
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spam:9
  template:
    metadata:
      labels:
        app: spam:9
    spec:
      containers:
      - name: spam:9
        image: akash300/spam:9
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: spam:9
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32002
  selector:
    app: spam:9
